### ISSUE TITLE
Minor enhancement: link to user profile on the discussion section

### ISSUE THREAD

**Issue by eordano** [Decentraland-DAO/transparency#16]
Currently, user names or avatars in the comments sections are not links. I think that for consistency, it would be good to be able to go to that user's profile as it is the case with the "Details" section
![image](https://user-images.githubusercontent.com/42750/184942704-dcdf1540-17ee-4e88-a52d-c1acf6623c5f.png)

**Comment by ncomerci** [comment]
Hi @eordano! It looks like you posted this issue in the wrong repo, please post it again here 🙌🏼https://github.com/decentraland/governance/issues

**Comment by andyesp** [comment]
Moved to Decentraland/governance#545
