### ISSUE TITLE
Voter Cohort Analysis Dashboard

### ISSUE THREAD

**Issue by ginocingolani** [Decentraland-DAO/transparency#69]
To show voter retention rate over last 12m
ref: https://twitter.com/DisruptionJoe/status/1703878805184450760/photo/1

**Comment by ginocingolani** [comment]
@ncomerci Update this :)

**Comment by ncomerci** [comment]
https://colab.research.google.com/drive/1jpduKVYGmrG_eWH9ispes4RGz5QwYpEV?usp=sharing
